import { describe, expect, it } from 'vitest';
import { buildAfterWarpScript, getInterpolatedVariableNames, getWarpVariableDrafts, hasAfterWarpLabel } from '@/lib/warpAfterWarp';

describe('warpAfterWarp helpers', () => {
  it('collects only default variables in a stable order', () => {
    const drafts = getWarpVariableDrafts(new Map([
      ['score', { name: 'score', type: 'default', initialValue: '0', definedInBlockId: 'b1', line: 1 }],
      ['player_name', { name: 'player_name', type: 'define', initialValue: '"Player"', definedInBlockId: 'b1', line: 2 }],
      ['chapter', { name: 'chapter', type: 'default', initialValue: '1', definedInBlockId: 'b1', line: 3 }],
    ]), []);

    expect(drafts).toEqual([
      { name: 'chapter', value: '1', source: 'default' },
      { name: 'score', value: '0', source: 'default' },
    ]);
  });

  it('collects interpolated variables and assigns default_<name> values', () => {
    const drafts = getWarpVariableDrafts(new Map(), [
      { id: 's1', sourceText: 'Hello [mc_name]!', blockId: 'b1', filePath: 'game/script.rpy', line: 1, labelScope: null, characterTag: null, type: 'dialogue' },
      { id: 's2', sourceText: 'Score: [points]', blockId: 'b1', filePath: 'game/script.rpy', line: 2, labelScope: null, characterTag: null, type: 'narration' },
    ]);

    expect(drafts).toEqual([
      { name: 'mc_name', value: 'default_mc_name', source: 'interpolated' },
      { name: 'points', value: 'default_points', source: 'interpolated' },
    ]);
  });

  it('extracts interpolated variable names from text expressions', () => {
    expect(getInterpolatedVariableNames([
      { id: 's1', sourceText: 'Hello [mc_name]! [points:.2f]', blockId: 'b1', filePath: 'game/script.rpy', line: 1, labelScope: null, characterTag: null, type: 'dialogue' },
    ])).toEqual(['mc_name', 'points']);
  });

  it('ignores config and ui files when scanning for interpolated variables', () => {
    expect(getInterpolatedVariableNames([
      { id: 's1', sourceText: 'Version [config.version]', blockId: 'b1', filePath: 'game/screens.rpy', line: 1, labelScope: null, characterTag: null, type: 'dialogue' },
      { id: 's2', sourceText: 'Style [config.name]', blockId: 'b2', filePath: 'game/options.rpy', line: 2, labelScope: null, characterTag: null, type: 'narration' },
      { id: 's3', sourceText: 'Hello [mc_name]', blockId: 'b3', filePath: 'game/scenes/stage1/stage1_evening.rpy', line: 3, labelScope: null, characterTag: null, type: 'dialogue' },
    ])).toEqual(['mc_name']);
  });

  it('detects an actual after_warp label only when present', () => {
    expect(hasAfterWarpLabel({
      after_warp: { blockId: 'b1', label: 'after_warp', line: 12, column: 1, type: 'label' },
    })).toBe(true);

    expect(hasAfterWarpLabel({
      after_warp: { blockId: 'b1', label: 'after_warp', line: 12, column: 1, type: 'menu' },
    })).toBe(false);

    expect(hasAfterWarpLabel({})).toBe(false);
  });

  it('builds a temporary after_warp script with optional fallback label', () => {
    expect(buildAfterWarpScript([
      { name: 'score', value: '10' },
      { name: 'player_name', value: '"Debug"' },
      { name: 'mc_name', value: 'default_mc_name', source: 'interpolated' },
    ], true)).toBe(
      [
        '# Generated by RenIDE for temporary warp overrides.',
        '# This file is removed automatically after the game stops.',
        '',
        'label after_warp:',
        '    $ score = 10',
        '    $ player_name = "Debug"',
        '    $ mc_name = "default_mc_name"',
        '    return',
        '',
      ].join('\n'),
    );
  });

  it('quotes plain text warp values while preserving expressions', () => {
    expect(buildAfterWarpScript([
      { name: 'mc_name', value: 'Alex', source: 'interpolated' },
      { name: 'chapter', value: 'persistent.chapter', source: 'default' },
    ], true)).toBe(
      [
        '# Generated by RenIDE for temporary warp overrides.',
        '# This file is removed automatically after the game stops.',
        '',
        'label after_warp:',
        '    $ mc_name = "Alex"',
        '    $ chapter = persistent.chapter',
        '    return',
        '',
      ].join('\n'),
    );
  });
});
